[tool.black]
line-length = 120
target-version = ['py310']

[tool.mypy]
exclude = ['examples']
ignore_missing_imports = true
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true

[tool.isort]
py_version=38
float_to_top = true
only_modified = true
follow_links = false
skip_gitignore = true
profile = "black"
line_length = 120

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ""
pythonpath = "src"
env = []